export const FIXED_32K_INPUT_TOKENS = 33_792
export const SHORT_INPUT_TOKENS = 320
export const EXPECTED_OUTPUT_TOKENS = 40
export const MAX_OUTPUT_TOKENS = 2_048

export const DEFAULT_INPUT_PRICE_PER_MILLION = 1.25
export const DEFAULT_OUTPUT_PRICE_PER_MILLION = 10
